[libraries]
androidGradlePlugin = "com.android.tools.build:gradle:8.0.2"
test-junit = "org.junit.jupiter:junit-jupiter:5.9.3"
test-strikt = "io.strikt:strikt-core:0.34.1"

[plugins]
kotlin = "org.jetbrains.kotlin.jvm:1.8.22"
wrapperUpgrade = "org.gradle.wrapper-upgrade:0.11.1"