[libraries]
androidGradlePlugin = "com.android.tools.build:gradle:7.4.1"
test-junit = "org.junit.jupiter:junit-jupiter:5.7.1"
test-strikt = "io.strikt:strikt-core:0.34.0"

[plugins]
kotlin = "org.jetbrains.kotlin.jvm:1.8.10"