name: 'Test Plugin'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  localPluginTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-caches-v0-${{ hashFiles('build.gradle.kts', 'settings.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}

      - name: Run 'normal' tests
        run: ./gradlew test --tests 'SentryProguardGradlePluginTest'

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

  publishingConsumingPluginTest:
    runs-on: ubuntu-latest
    env:
      IOKI_SENTRY_PROGUARD_PLUGIN_TEST_VERSION: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-caches-v0-${{ hashFiles('build.gradle.kts', 'settings.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}

      - name: Publish Plugin to mavenLocal
        run: ./gradlew publishToMavenLocal

      - name: Run publishing/consuming tests
        run: ./gradlew test --tests 'SentryProguardGradlePluginPublishingTest'

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'